apiVersion: apps/v1
kind: Deployment
metadata:
  name: arsis-deployment
  namespace: nyantech
  labels:
    app: arsis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arsis
  template:
    metadata:
      labels:
        app: arsis
    spec:
      containers:
      - name: arsis
        image: ghcr.io/atis9/arsis:latest
        imagePullPolicy: Always
        env:
          - name: DISCORD_TOKEN
            valueFrom:
              secretKeyRef:
                name: arsis-secret
                key: discord-token
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
