apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: nyantech
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: github-actions:repo:Atis9/arsis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nyantech-admin
